# Generated by Django 5.2.1 on 2025-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код риска')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('risk_type', models.CharField(max_length=100, verbose_name='Тип риска')),
                ('source', models.CharField(max_length=255, verbose_name='Источник')),
                ('registered_at', models.DateField(verbose_name='Дата регистрации')),
                ('department', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец риска')),
                ('process', models.CharField(max_length=255, verbose_name='Процесс')),
                ('probability', models.IntegerField(verbose_name='Вероятность (1–5)')),
                ('impact', models.IntegerField(verbose_name='Воздействие (1–5)')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень риска')),
            ],
        ),
    ]
