# Generated by Django 5.2.1 on 2025-06-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0003_department_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_app.division', verbose_name='Отдел'),
        ),
    ]
