# Generated by Django 5.2.1 on 2025-06-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0004_controlpoint_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_app.department', verbose_name='Департамент'),
        ),
    ]
