# Generated by Django 5.2.1 on 2025-06-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0005_controlpoint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='department',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='control_app.department'),
            preserve_default=False,
        ),
    ]
