# Generated by Django 5.2.1 on 2025-06-16 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0008_department_name_en_department_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='related_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_control_points', to='control_app.risk', verbose_name='Related Risk'),
        ),
    ]
