# Generated by Django 5.2.1 on 2025-06-23 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0009_controlpoint_related_risk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processdiagram',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='processdiagram',
            name='bpmn_xml',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processdiagram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processdiagram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processdiagram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.department'),
        ),
        migrations.AlterField(
            model_name='processdiagram',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.division'),
        ),
        migrations.AlterField(
            model_name='processdiagram',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
