# Generated by Django 5.2.1 on 2025-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.IntegerField(verbose_name='Impact (1–5)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.IntegerField(verbose_name='Probability (1–5)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='process',
            field=models.CharField(max_length=255, verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='registered_at',
            field=models.DateField(verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Risk Code'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_type',
            field=models.CharField(max_length=100, verbose_name='Risk Type'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Source'),
        ),
    ]
