# Generated by Django 5.0.6 on 2025-06-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0008_department_name_en_department_name_ru_and_more'),
        ('risk_app', '0002_alter_risk_department_alter_risk_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_app.department', verbose_name='Department'),
        ),
    ]
